version: '3.5'
services:
  master:
    build: ./
    networks:
      - jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:

volumes:
  jenkins_data:
